# Generated by Django 3.1.7 on 2021-04-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('category', models.SmallIntegerField(choices=[(0, 'Все'), (1, 'Игровые новости'), (2, 'Технологии'), (3, 'Софт'), (4, 'Новости киноиндустрии')], default=0)),
                ('draft', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ('id', 'draft'),
            },
        ),
    ]
